/**
 * Combines all test case files into one large file for performance testing
 */
import fs from 'fs';
import path from 'path';

const exampleSrcDir = path.join(__dirname, '..', 'example', 'src');
const outputFile = path.join(__dirname, 'test-files', 'AllUseCases.tsx');

// Get all .tsx files that aren't spec files
const files = fs
	.readdirSync(exampleSrcDir)
	.filter(f => f.endsWith('.tsx') && !f.includes('.spec.'));

console.log('Found test case files:');
files.forEach(f => console.log(`  - ${f}`));
console.log();

// Combine all files
let combined = `/**
 * Combined test cases for performance benchmarking
 * This file contains all className usage patterns from the test suite
 *
 * Generated by: performance/combine-test-cases.ts
 * Source: example/src/*.tsx
 */
import React from 'react';

`;

files.forEach((file, index) => {
	const filePath = path.join(exampleSrcDir, file);
	const content = fs.readFileSync(filePath, 'utf-8');

	// Remove import statements and just take the function definitions
	const lines = content.split('\n');
	const withoutImports = lines.filter(line => !line.trim().startsWith('import ')).join('\n');

	combined += `\n// ============================================================\n`;
	combined += `// From: ${file}\n`;
	combined += `// ============================================================\n`;
	combined += withoutImports;
	combined += '\n';
});

// Add a main component that uses all the patterns
combined += `\n// ============================================================\n`;
combined += `// Main component for benchmarking\n`;
combined += `// ============================================================\n`;
combined += `export function AllUseCases() {\n`;
combined += `  return (\n`;
combined += `    <div className="container mx-auto p-4">\n`;
combined += `      <h1 className="text-3xl font-bold mb-8">All Use Cases</h1>\n`;
combined += `      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">\n`;

files.forEach((file, index) => {
	// Extract function names from each file
	const filePath = path.join(exampleSrcDir, file);
	const content = fs.readFileSync(filePath, 'utf-8');
	const functionMatches = content.matchAll(/export function (\w+)/g);

	for (const match of functionMatches) {
		const functionName = match[1];
		combined += `        <div className="border rounded p-4">\n`;
		combined += `          <h3 className="font-semibold mb-2">${functionName}</h3>\n`;
		combined += `          <${functionName} />\n`;
		combined += `        </div>\n`;
	}
});

combined += `      </div>\n`;
combined += `    </div>\n`;
combined += `  );\n`;
combined += `}\n`;

// Write the combined file
fs.writeFileSync(outputFile, combined);

// Get stats
const stats = fs.statSync(outputFile);
const lines = combined.split('\n').length;
const classNameCount = (combined.match(/className/g) || []).length;

console.log('Combined file created:');
console.log(`  Path: ${outputFile}`);
console.log(`  Size: ${(stats.size / 1024).toFixed(2)} KB`);
console.log(`  Lines: ${lines}`);
console.log(`  className usages: ${classNameCount}`);
console.log();
